import { Sunflower, Geist_Mono } from "next/font/google";
import '@/styles/globals.css';

const sunflower = Sunflower({ 
  weight: ['300', '500', '700'], // Specify available weights
  subsets: ['latin'] // Required subset
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sunflower.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
